### ISSUE TITLE
Can quiz on the same word indefinitely

### ISSUE THREAD

**Issue by domino14** [domino14/Webolith#104]
![11059627_961846250524_326517897005734208_n](https://cloud.githubusercontent.com/assets/585318/9295642/31606654-4429-11e5-9d01-6307ed0f3d1e.jpg)

"I think a few different things can cause it, but quiz on missed when there's only 1 word left and you type the word in more than once seems to always produce it for me, indefinitely"

**Comment by volucrisscr** [comment]
Tested again, more than 1 word in this missed wordwall but I could still enter the last one in over and over.
![screenshot_480](https://cloud.githubusercontent.com/assets/13701965/9314992/63254f02-44fa-11e5-9ff0-35fd88d90851.png)

**Comment by volucrisscr** [comment]
Doesn't have to be missed at all. I guess it's all quizzes.
![screenshot_481](https://cloud.githubusercontent.com/assets/13701965/9315044/c1d9463e-44fa-11e5-990b-78b8d4d454ed.png)
At least that's not reflected in Daily Challenge results or anything like that.

**Comment by domino14** [comment]
does the quiz actually end when this happens? I guess I should test it too.

**Comment by volucrisscr** [comment]
Thought of something else today -- not necessarily the last word, but all solutions to the last anagram work. (When it's not the last anagram left it doesn't work.)
![screenshot_502](https://cloud.githubusercontent.com/assets/13701965/9392324/172417b2-474a-11e5-8508-663288ae2f84.png)

**Comment by volucrisscr** [comment]
The quiz ends in all the obvious user facing ways -- the screen clears, the Solutions window is available. The bug is just that you can keep answering after this, and have the answers show up in the correct answers box and affect your stats.

**Comment by domino14** [comment]
Thanks! I'll get back into bug-fixing mode soon.

I'm strongly thinking of doing Aerolith (and other side projects?) coding
on livecoding.tv a few hours a week. It probably won't be fun to watch, but
it'll help keep me focused! I'll write more details somewhere soon.
