### ISSUE TITLE
Deletion of saved list isn't reducing the total number of alphagrams

### ISSUE THREAD

**Issue by seanigan** [domino14/Webolith#117]
My account is seanigan, there is a 15, 000 anagram limit on my account and I have roughly 3000 alphagrams over my current saved lists (the 4's).

But I see the following 'You have 13175 alphagrams over all your saved lists. Your current limit is 15000. You can increase this by becoming a supporter!'

I deleted a bunch of lists but the total didn't go down.

**Comment by domino14** [comment]
This is probably because you have lists in old lexica that have not been deleted. I see you have some old OWL2 lists. I can delete these for you if you want?

**Comment by domino14** [comment]
#118

**Comment by seanigan** [comment]
Hi Cesar

Sure delete those

Thanks

**Comment by domino14** [comment]
Done!
