### ISSUE TITLE
Upgrade to Python 3

### ISSUE THREAD

**Issue by domino14** [domino14/Webolith#223]

**Comment by oliver-daniel** [comment]
Are there any particular files that need updating? I would be happy to take this on if so.

**Comment by domino14** [comment]
That would be awesome, but it's the entirety of the Python codebase!

**Comment by oliver-daniel** [comment]
Great! I'll get on it. Just for reference, I've included the output of using the Flake8 linter (for Python 3) before and after wrapping all the print statement in parentheses and silencing some of the style quibbles.
[Before](https://github.com/domino14/Webolith/files/931672/flake8-output.txt)
[After](https://github.com/domino14/Webolith/files/931673/flake8-output-new.txt)

**Comment by domino14** [comment]
awesome!

**Comment by domino14** [comment]
Still want to do this? :)

**Comment by domino14** [comment]
😢

**Comment by domino14** [comment]
😠

**Comment by brainforecast** [comment]
Alright, let's do this. Tedious, but a good development opportunity for me.

I will attempt to clone Aerolith by Friday in an effort to start making .py syntax upgrades on the weekend.

**Comment by domino14** [comment]
yay!

**Comment by brainforecast** [comment]
Heads up- Fabric doesn't support Python 3, it sounds like anybody using it now uses Fabric3 (different team) which I haven't heard complaints about. It's meant to be easily replaced as far as code goes.

**Comment by brainforecast** [comment]
So here's my issue. Syntactically moving from py2 to py3 should be doable, but I obviously want to test it locally before contributing. I'm finding creating a clone pretty difficult as I'm unfamiliar with Go and databases in general.

Instead, what I can (have started to) do is make a "best effort" attempt but I'm not sure how to verify that it will be bug-free in the grand scheme.

**Comment by domino14** [comment]
Yeah I understand, I'm also updating the codebase a bunch. I don't have a good fast way of creating a clone yet. Maybe it's ok - I can handle it or continue your work if any? Thank you anyway!

**Comment by domino14** [comment]
Yeah I understand, I'm also updating the codebase a bunch. I don't have a good fast way of creating a clone yet. Maybe it's ok - I can handle it or continue your work if any? Thank you anyway!
